project:
  type: website
  output-dir: _site
  preview:
    port: 4200
    browser: true

execute:
  freeze: auto

website:
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  open-graph: true
  search: true
  twitter-card: true
  title: "No Code Data Visualization"
  site-url: "https://nocodeviz.netlify.app"
  repo-url: ""
  description: This is the teaching website of Arvind V., External Faculty, Srishti Manipal Institute of Art, Design, and Technology, Bangalore, India.
  favicon: "content/materials/icon-park-twotone--concept-sharing.svg"
  google-analytics: "" 
  reader-mode: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    background: secondary
    alignment: left
    collapse-level: 2
    search: true
    logo: "content/materials/images/1book25.jpg"
    contents:
      - section: "No Code Data Viz"
        href: content/courses/NoCodeViz/listing.qmd
        contents: 
        - content/courses/NoCodeDataViz/Modules/05-NatureData/index.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



